import {
  BadgeCheck,
  CalendarCheck,
  Camera,
  Car,
  Droplets,
  FileText,
  GraduationCap,
  Hammer,
  HeartPulse,
  Headset,
  Laptop,
  LockKeyhole,
  Paintbrush,
  Scale,
  Sparkles,
  Truck,
  Users,
  Wallet,
  Zap,
} from "lucide-react";
import type {
  Category,
  Feature,
  Specialist,
  Step,
  Testimonial,
} from "../types/types";

export const categories: Category[] = [
  {
    id: "repairs",
    label: "تعمیرات و نگهداری ساختمان",
    count: 1800,
    icon: Hammer,
    tint: "bg-orange-500/10 text-orange-600",
    href: "/services/repairs",
  },
  {
    id: "cleaning",
    label: "نظافت و خدمات منزل",
    count: 1250,
    icon: Sparkles,
    tint: "bg-sky-500/10 text-sky-600",
    href: "/services/cleaning",
  },
  {
    id: "electrical",
    label: "برق‌کاری",
    count: 940,
    icon: Zap,
    tint: "bg-amber-500/10 text-amber-600",
    href: "/services/electrical",
  },
  {
    id: "plumbing",
    label: "لوله‌کشی و تأسیسات",
    count: 870,
    icon: Droplets,
    tint: "bg-cyan-500/10 text-cyan-600",
    href: "/services/plumbing",
  },
  {
    id: "painting",
    label: "نقاشی و دکوراسیون",
    count: 720,
    icon: Paintbrush,
    tint: "bg-rose-500/10 text-rose-600",
    href: "/services/painting",
  },
  {
    id: "moving",
    label: "اسباب‌کشی و حمل‌ونقل",
    count: 610,
    icon: Truck,
    tint: "bg-emerald-500/10 text-emerald-600",
    href: "/services/moving",
  },
  {
    id: "education",
    label: "آموزش و تدریس خصوصی",
    count: 2100,
    icon: GraduationCap,
    tint: "bg-indigo-500/10 text-indigo-600",
    href: "/services/education",
  },
  {
    id: "legal",
    label: "حقوقی و مشاوره",
    count: 430,
    icon: Scale,
    tint: "bg-violet-500/10 text-violet-600",
    href: "/services/legal",
  },
  {
    id: "tech",
    label: "طراحی و برنامه‌نویسی",
    count: 1560,
    icon: Laptop,
    tint: "bg-teal-500/10 text-teal-600",
    href: "/services/tech",
  },
  {
    id: "photo",
    label: "عکاسی و فیلم‌برداری",
    count: 520,
    icon: Camera,
    tint: "bg-pink-500/10 text-pink-600",
    href: "/services/photo",
  },
  {
    id: "health",
    label: "سلامت و زیبایی",
    count: 690,
    icon: HeartPulse,
    tint: "bg-red-500/10 text-red-600",
    href: "/services/health",
  },
  {
    id: "auto",
    label: "خودرو و مکانیکی",
    count: 480,
    icon: Car,
    tint: "bg-lime-500/10 text-lime-700",
    href: "/services/auto",
  },
];

export const steps: Step[] = [
  {
    icon: FileText,
    title: "نیازتان را توضیح دهید",
    description: "بگویید چه کاری لازم دارید و جزئیات آن را بنویسید.",
  },
  {
    icon: Users,
    title: "متخصصان را مقایسه کنید",
    description: "متخصصان تأییدشده را بر اساس امتیاز، قیمت و تجربه بررسی کنید.",
  },
  {
    icon: BadgeCheck,
    title: "بهترین گزینه را انتخاب کنید",
    description: "متخصصی که با کار و بودجه‌ی شما جور است را انتخاب کنید.",
  },
  {
    icon: CalendarCheck,
    title: "زمان را تنظیم و کار را تمام کنید",
    description: "زمان مراجعه را هماهنگ کنید و با خیال راحت کارتان را انجام دهید.",
  },
];

export const specialists: Specialist[] = [
  {
    id: "ali-rezaei",
    name: "علی رضایی",
    field: "لوله‌کش ساختمان",
    rating: 4.9,
    reviews: 312,
    jobs: 210,
    city: "تهران",
    startingPrice: 350000,
    verified: true,
  },
  {
    id: "sara-ahmadi",
    name: "سارا احمدی",
    field: "نقاش و دکوراتور",
    rating: 4.7,
    reviews: 128,
    jobs: 80,
    city: "اصفهان",
    startingPrice: 400000,
    verified: true,
  },
  {
    id: "maryam-hosseini",
    name: "مریم حسینی",
    field: "وکیل پایه یک دادگستری",
    rating: 4.9,
    reviews: 96,
    jobs: 150,
    city: "تهران",
    startingPrice: 1200000,
    verified: true,
  },
  {
    id: "nima-sadeghi",
    name: "نیما صادقی",
    field: "طراح UI/UX",
    rating: 4.8,
    reviews: 74,
    jobs: 60,
    city: "شیراز",
    startingPrice: 900000,
    verified: true,
  },
  {
    id: "pariya-mousavi",
    name: "پریا موسوی",
    field: "مدرس خصوصی ریاضی",
    rating: 5,
    reviews: 203,
    jobs: 340,
    city: "مشهد",
    startingPrice: 300000,
    verified: true,
  },
  {
    id: "amir-karimi",
    name: "امیر کریمی",
    field: "نجار و مبلمان سفارشی",
    rating: 4.8,
    reviews: 88,
    jobs: 55,
    city: "تبریز",
    startingPrice: 450000,
    verified: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    name: "الهام ر.",
    city: "تهران",
    service: "نقاشی ساختمان",
    text: "نقاش‌مان در یک آخر هفته نشیمن را کامل عوض کرد. رزرو و پرداخت هم خیلی راحت بود.",
    rating: 5,
  },
  {
    name: "حامد ک.",
    city: "شیراز",
    service: "مشاوره حقوقی",
    text: "توی کمتر از یک ساعت چند وکیل را با هم مقایسه کردم و همان روز وقت مشاوره گرفتم.",
    rating: 5,
  },
  {
    name: "نگار م.",
    city: "مشهد",
    service: "تدریس خصوصی",
    text: "برای پسرم معلم ریاضی پیدا کردم. نظرات واقعی بقیه‌ی مشتریان خیلی در انتخابم کمک کرد.",
    rating: 4,
  },
];

export const features: Feature[] = [
  {
    icon: LockKeyhole,
    title: "پرداخت امن",
    description: "با خیال جمع و در امنیت کامل از طریق هلپر پرداخت کنید.",
  },
  {
    icon: Wallet,
    title: "قیمت‌گذاری شفاف",
    description: "قیمت پایه را از قبل ببینید، بدون هیچ هزینه‌ی پنهانی.",
  },
  {
    icon: BadgeCheck,
    title: "متخصصان تأییدشده",
    description: "همه‌ی متخصصان از نظر سابقه و هویت بررسی و تأیید شده‌اند.",
  },
  {
    icon: Headset,
    title: "پشتیبانی مشتریان",
    description: "هر وقت نیاز داشتید، کمک واقعی در دسترستان هست.",
  },
];